import { Cart, Product, ShippingAddress } from '@/types'
import { DEFAULT_PAYMENT_METHOD } from './constants'

export const demoProducts: Product[] = [
  {
    id: 'demo-machinery-1',
    name: 'Field Tractor XT 45HP',
    slug: 'field-tractor-xt-45hp',
    category: 'Machinery',
    images: ['/images/products/card-machinery.png'],
    brand: 'BKM Agro',
    description: 'Reliable tractor for ploughing, haulage, and field transport.',
    stock: 5,
    price: '625000.00',
    rating: '4.6',
    numReviews: 124,
    isFeatured: true,
    banner: '/images/home/hero-machinery.png',
    createdAt: new Date(),
  },
  {
    id: 'demo-mro-1',
    name: 'Industrial Tool Kit 72P',
    slug: 'industrial-tool-kit-72p',
    category: 'MRO',
    images: ['/images/products/card-mro.png'],
    brand: 'FixWell',
    description: 'Heavy-duty MRO toolkit for farm and workshop maintenance.',
    stock: 34,
    price: '5200.00',
    rating: '4.3',
    numReviews: 98,
    isFeatured: true,
    banner: '/images/home/hero-mro.png',
    createdAt: new Date(),
  },
  {
    id: 'demo-seeds-1',
    name: 'Hybrid Paddy Seeds (5kg)',
    slug: 'hybrid-paddy-seeds-5kg',
    category: 'Seeds',
    images: ['/images/products/card-seeds.png'],
    brand: 'GreenGrow',
    description: 'High-germination paddy seeds for improved yield.',
    stock: 120,
    price: '1750.00',
    rating: '4.7',
    numReviews: 204,
    isFeatured: false,
    banner: '/images/home/hero-seeds.png',
    createdAt: new Date(),
  },
  {
    id: 'demo-fertilizer-1',
    name: 'NPK Fertilizer Mix',
    slug: 'npk-fertilizer-mix',
    category: 'Fertilizers',
    images: ['/images/products/card-seeds.png'],
    brand: 'CropPlus',
    description: 'Balanced nutrient blend for strong root and canopy growth.',
    stock: 200,
    price: '980.00',
    rating: '4.2',
    numReviews: 76,
    isFeatured: false,
    banner: '/images/home/hero-deals.png',
    createdAt: new Date(),
  },
]

export const demoAddress: ShippingAddress = {
  fullName: 'Demo Farmer',
  streetAddress: 'Village Road 1',
  city: 'Bikaner',
  postalCode: '334001',
  country: 'India',
  lat: 0,
  lng: 0,
}

export const demoCart: Cart = {
  id: 'demo-cart',
  userId: null,
  sessionCartId: 'demo-session',
  items: [
    {
      productId: 'demo-seeds-1',
      name: 'Hybrid Paddy Seeds (5kg)',
      slug: 'hybrid-paddy-seeds-5kg',
      qty: 1,
      image: '/images/products/card-seeds.png',
      price: 1750,
    },
  ],
  itemsPrice: '1750.00',
  shippingPrice: '0.00',
  taxPrice: '262.50',
  totalPrice: '2012.50',
  createdAt: new Date(),
}

export const demoUser = (userId?: string) => ({
  id: userId || 'demo-user',
  name: 'Demo User',
  email: 'demo@example.com',
  role: 'user',
  password: null,
  emailVerified: null,
  image: null,
  address: demoAddress,
  paymentMethod: DEFAULT_PAYMENT_METHOD,
  createdAt: new Date(),
})

